server:
  port: 8082
spring:
  application:
    name: maven-research-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-mercury-container:3306/mercury?useSSL=false

    hikari:
      minimumIdle: 4
      idleTimeout: 600000
      maximumPoolSize: 8
      connectionTimeout: 30000
      maxLifetime: 1800000
grpc:
  port: 8072