version: "3"
services:
  mercury-service:
    image: nghiatn/mercury-service:1.0-SNAPSHOT
    ports:
      - "8082"
      - "8072"
    networks:
      - mercury_network
    depends_on:
      - mysql-mercury

  mysql-mercury:
    container_name: mysql-mercury-container
    image: nghiatn/mysql-mercury:1.0-SNAPSHOT
    command: --default-authentication-plugin=mysql_native_password
    # port is optional, comment it if the conflict occur
    ports:
      - "3306:3306"
    networks:
      - mercury_network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mercury-service
    ports:
      - "8082:8082"
    networks:
      - mercury_network

networks:
  mercury_network: