version: "3"
services:
  mercury-service:
    container_name: mercury-service-container
    image: mercury-service
    ports:
      - "8082:8082"
      - "8072:8072"
    networks:
      - mercury_network
    depends_on:
      - mysql-mercury

  mysql-mercury:
    container_name: mysql-mercury-container
    image: mysql-mercury
    command: --default-authentication-plugin=mysql_native_password
    # port is optional, comment it if the conflict occur
    ports:
      - "3306:3306"
    networks:
      - mercury_network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root

networks:
  mercury_network: