version: '3.7'
services:
  mysql:
    container_name: mysql-maven
    image: nghiatn/mysql-maven:1.0
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: